# Generated by Django 2.2 on 2021-05-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_regapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('plan', models.CharField(max_length=255)),
                ('startdate', models.CharField(max_length=255)),
                ('enddate', models.CharField(max_length=255)),
                ('traveler', models.ManyToManyField(related_name='travel', to='login_regapp.Userreg')),
            ],
        ),
    ]
