# Generated by Django 2.2 on 2021-06-27 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_regapp', '0002_destination'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Destination',
        ),
    ]
